"""genhelp.py -- emit a cvar-help table from QVM data.

Usage:
  python genhelp.py <qvm> <table_base_vm> <count_addr_vm> <out.h> [stride]

Default stride 40. Row: +0 vmCvar, +4 name, +8 default, +12 flags, …
+24 kind, +28 min str, +32 max str, +36 help str.
Mod-specific addresses belong on the command line, not in this file.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qvmstr import QvmStrings


def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


def main():
    qvm_path, base, count_addr, out_path = sys.argv[1], int(sys.argv[2], 0), int(sys.argv[3], 0), sys.argv[4]
    stride = int(sys.argv[5], 0) if len(sys.argv) > 5 else 40
    q = QvmStrings(qvm_path)

    n = q.word(count_addr)
    rows = []
    for k in range(n):
        r = base + stride * k
        f = q.words(r, 10)
        try:
            name = q.cstr(f[1])
        except ValueError:
            continue
        try:
            mn = q.cstr(f[7]) if f[7] else ''
            mx = q.cstr(f[8]) if f[8] else ''
            hp = q.cstr(f[9]) if f[9] else ''
        except ValueError:
            mn = mx = hp = ''
        rows.append((name, f[6] or 0, mn or '', mx or '', hp or ''))

    out = [
        '// Generated by tools/scripts/genhelp.py from %s' % qvm_path,
        '// cvar table base VM=%d stride=%d count=%d' % (base, stride, n),
        'typedef struct {',
        '\tconst char *name;',
        '\tint         kind;',
        '\tconst char *min;',
        '\tconst char *max;',
        '\tconst char *help;',
        '} cvarHelpInfo_t;',
        '',
        'static const cvarHelpInfo_t cvarHelpTable[] = {',
    ]
    for name, kind, mn, mx, hp in rows:
        out.append('\t{ "%s", %d, "%s", "%s", "%s" },' % (esc(name), kind, esc(mn), esc(mx), esc(hp)))
    out.append('};')

    open(out_path, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    print('rows: %d -> %s' % (len(rows), out_path))


if __name__ == '__main__':
    main()
